### ISSUE TITLE
Endless promotion in Ranked

### ISSUE THREAD

**Issue by JohSchillerEmnify** [bakkesmodorg/BakkesModInjectorCpp#13]
Whenever i start the game with bakkesmod loaded i will get the "promoted" notification after every single game, regardless if won or lost. It says "33(goes up every match) of 10 games played" and then gives me the promotion, as if it doesn't realize that 33 is not a valid number for this behavior. Not loading bakkesmod prevents this, but as soon as i load it again it shows up again. 

I can provide further info on when exactly this occurs and any other info necessary. 

To add some detail, i now tried reinstalling bakkesmod completely (also deleting the appdata folder) and as soon as i enable "show MMR on scoreboard" the bug appears again.

**Comment by joao-conde** [comment]
This is the only bug I have found so far, a really unpleasant one. Apart from that Bakkes is perfect to me. This should be given high priority IMO.

**Comment by JohSchillerEmnify** [comment]
This particular Bug seems to be fixed with the latest release, although I now missed at least one promotion notification. But that might be a red herring. Will close this for now.
