### ISSUE TITLE
Can't install without a GUI

### ISSUE THREAD

**Issue by CaptainGlac1er** [bakkesmodorg/BakkesModInjectorCpp#23]
I think these MsgBox are blocking the ability to install this from powershell. Currently it forces you to install through a gui.  https://github.com/bakkesmodorg/BakkesModInjectorCpp/blob/25203381370e6866de35b4071264db2006c43e1b/installer.iss#L103

**Comment by Bakkes** [comment]
It's not the cleanest param name for this, but you should be able to use `/installfromdll=true` to suppress these message boxes.

`BakkesModSetup.exe /VERYSILENT /installfromdll=true` installs without any message boxes for me.

https://github.com/bakkesmodorg/BakkesModInjectorCpp/blob/25203381370e6866de35b4071264db2006c43e1b/installer.iss#L95
